name: db-reset-daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  reset-db:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: TRUNCATE tables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql "$DATABASE_URL" -v ON_ERROR_STOP=1 \
            -c "TRUNCATE TABLE users RESTART IDENTITY CASCADE;"
